PySCIPOpt: Row Class Reference
Row Class Reference
Public Member Functions
def __eq__ (self, other)
def __get__ (self)
def __hash__ (self)
def getBasisStatus (self)
def getCols (self)
def getConstant (self)
def getLhs (self)
def getLPPos (self)
def getNLPNonz (self)
def getNNonz (self)
def getNorm (self)
def getOrigintype (self)
def getRhs (self)
def getVals (self)
def isInGlobalCutpool (self)
def isIntegral (self)
def isLocal (self)
def isModifiable (self)
def isRemovable (self)
Static Public Attributes
row = Row()
scip_row
Detailed Description
Base class holding a pointer to corresponding SCIP_ROW
Definition at line 382 of file scip.pyx.
Member Function Documentation
__eq__()
def __eq__ (self, other)
Definition at line 478 of file scip.pyx.
References Event.__class__, Column.__class__, Row.__class__, and Row.scip_row.
__get__()
def __get__ (self)
Definition at line 394 of file scip.pyx.
References Row.scip_row, and SCIProwGetName().
__hash__()
def __hash__ (self)
Definition at line 475 of file scip.pyx.
References Row.scip_row.
getBasisStatus()
def getBasisStatus (self)
gets the basis status of a row in the LP solution, Note: returns basis status `basic` for rows not in the current SCIP LP
Definition at line 414 of file scip.pyx.
References Row.scip_row, and SCIProwGetBasisStatus().
getCols()
def getCols (self)
gets list with columns of nonzero entries
Definition at line 461 of file scip.pyx.
References Row.getNNonz(), Row.scip_row, and SCIProwGetCols().
getConstant()
def getConstant (self)
gets constant shift of row
Definition at line 406 of file scip.pyx.
References Row.scip_row, and SCIProwGetConstant().
getLhs()
def getLhs (self)
returns the left hand side of row
Definition at line 398 of file scip.pyx.
References Row.scip_row, and SCIProwGetLhs().
getLPPos()
def getLPPos (self)
gets position of row in current LP, or -1 if it is not in LP
Definition at line 410 of file scip.pyx.
References Row.scip_row, and SCIProwGetLPPos().
getNLPNonz()
def getNLPNonz (self)
get number of nonzero entries in row vector that correspond to columns currently in the SCIP LP
Definition at line 457 of file scip.pyx.
References Row.scip_row, and SCIProwGetNLPNonz().
getNNonz()
def getNNonz (self)
get number of nonzero entries in row vector
Definition at line 453 of file scip.pyx.
References Row.scip_row, and SCIProwGetNNonz().
getNorm()
def getNorm (self)
gets Euclidean norm of row vector
Definition at line 471 of file scip.pyx.
References Row.scip_row, and SCIProwGetNorm().
getOrigintype()
def getOrigintype (self)
returns type of origin that created the row
Definition at line 449 of file scip.pyx.
References Row.scip_row, and SCIProwGetOrigintype().
getRhs()
def getRhs (self)
returns the right hand side of row
Definition at line 402 of file scip.pyx.
References Row.scip_row, and SCIProwGetRhs().
getVals()
def getVals (self)
gets list with coefficients of nonzero entries
Definition at line 466 of file scip.pyx.
References Row.getNNonz(), Row.scip_row, and SCIProwGetVals().
isInGlobalCutpool()
def isInGlobalCutpool (self)
return TRUE iff row is a member of the global cut pool
Definition at line 445 of file scip.pyx.
References Row.scip_row, and SCIProwIsInGlobalCutpool().
isIntegral()
def isIntegral (self)
returns TRUE iff the activity of the row (without the row's constant) is always integral in a feasible solution
Definition at line 429 of file scip.pyx.
References Row.scip_row, and SCIProwIsIntegral().
isLocal()
def isLocal (self)
returns TRUE iff the row is only valid locally
Definition at line 433 of file scip.pyx.
References Row.scip_row, and SCIProwIsLocal().
isModifiable()
def isModifiable (self)
returns TRUE iff row is modifiable during node processing (subject to column generation)
Definition at line 437 of file scip.pyx.
References Row.scip_row, and SCIProwIsModifiable().
isRemovable()
def isRemovable (self)
returns TRUE iff row is removable from the LP (due to aging or cleanup)
Definition at line 441 of file scip.pyx.
References Row.scip_row, and SCIProwIsRemovable().
Member Data Documentation
row
row = Row() static
Definition at line 389 of file scip.pyx.
scip_row
scip_row static
Definition at line 390 of file scip.pyx.
The documentation for this class was generated from the following file:
src/pyscipopt/scip.pyx