PySCIPOpt: Event Class Reference
Event Class Reference
Public Member Functions
def __eq__ (self, other)
def __hash__ (self)
def __repr__ (self)
def getNewBound (self)
def getNode (self)
def getOldBound (self)
def getRow (self)
def getType (self)
def getVar (self)
Static Public Attributes
event = Event()
Detailed Description
Base class holding a pointer to corresponding SCIP_EVENT
Definition at line 273 of file scip.pyx.
Member Function Documentation
__eq__()
def __eq__ (self, other)
Definition at line 317 of file scip.pyx.
References Event.__class__, and Event.event.
__hash__()
def __hash__ (self)
Definition at line 314 of file scip.pyx.
References Event.event.
__repr__()
def __repr__ (self)
Definition at line 288 of file scip.pyx.
References Event.getType().
getNewBound()
def getNewBound (self)
gets new bound for a bound change event
Definition at line 291 of file scip.pyx.
References Event.event, and SCIPeventGetNewbound().
getNode()
def getNode (self)
gets node for a node or LP event
Definition at line 304 of file scip.pyx.
References Event.event, and SCIPeventGetNode().
getOldBound()
def getOldBound (self)
gets old bound for a bound change event
Definition at line 295 of file scip.pyx.
References Event.event, and SCIPeventGetOldbound().
getRow()
def getRow (self)
gets row for a row event
Definition at line 309 of file scip.pyx.
References Event.event, and SCIPeventGetRow().
getType()
def getType (self)
gets type of event
Definition at line 284 of file scip.pyx.
References Event.event, and SCIPeventGetType().
getVar()
def getVar (self)
gets variable for a variable event (var added, var deleted, var fixed, objective value or domain change, domain hole added or removed)
Definition at line 299 of file scip.pyx.
References Event.event, and SCIPeventGetVar().
Member Data Documentation
event
event = Event() static
Definition at line 280 of file scip.pyx.
The documentation for this class was generated from the following file:
src/pyscipopt/scip.pyx