PySCIPOpt: Column Class Reference
Column Class Reference
Public Member Functions
def __eq__ (self, other)
def __hash__ (self)
def getBasisStatus (self)
def getLb (self)
def getLPPos (self)
def getObjCoeff (self)
def getPrimsol (self)
def getUb (self)
def getVar (self)
def isIntegral (self)
Static Public Attributes
col = Column()
scip_col
Detailed Description
Base class holding a pointer to corresponding SCIP_COL
Definition at line 321 of file scip.pyx.
Member Function Documentation
__eq__()
def __eq__ (self, other)
Definition at line 378 of file scip.pyx.
References Event.__class__, Column.__class__, and Column.scip_col.
__hash__()
def __hash__ (self)
Definition at line 375 of file scip.pyx.
References Column.scip_col.
getBasisStatus()
def getBasisStatus (self)
gets the basis status of a column in the LP solution, Note: returns basis status `zero` for columns not in the current SCIP LP
Definition at line 336 of file scip.pyx.
References Column.scip_col, and SCIPcolGetBasisStatus().
getLb()
def getLb (self)
gets lower bound of column
Definition at line 363 of file scip.pyx.
References Column.scip_col, and SCIPcolGetLb().
getLPPos()
def getLPPos (self)
gets position of column in current LP, or -1 if it is not in LP
Definition at line 332 of file scip.pyx.
References Column.scip_col, and SCIPcolGetLPPos().
getObjCoeff()
def getObjCoeff (self)
gets objective value coefficient of a column
Definition at line 371 of file scip.pyx.
References Column.scip_col, and SCIPcolGetObj().
getPrimsol()
def getPrimsol (self)
gets the primal LP solution of a column
Definition at line 359 of file scip.pyx.
References Column.scip_col, and SCIPcolGetPrimsol().
getUb()
def getUb (self)
gets upper bound of column
Definition at line 367 of file scip.pyx.
References Column.scip_col, and SCIPcolGetUb().
getVar()
def getVar (self)
gets variable this column represents
Definition at line 354 of file scip.pyx.
References Column.scip_col, and SCIPcolGetVar().
isIntegral()
def isIntegral (self)
returns whether the associated variable is of integral type (binary, integer, implicit integer)
Definition at line 350 of file scip.pyx.
References Column.scip_col, and SCIPcolIsIntegral().
Member Data Documentation
col
col = Column() static
Definition at line 328 of file scip.pyx.
scip_col
scip_col static
Definition at line 329 of file scip.pyx.
The documentation for this class was generated from the following file:
src/pyscipopt/scip.pyx